on: [release, workflow_dispatch]
name: Release
jobs:
#   iosRelease:
#     runs-on: macos-latest
#     steps:
#       - name: Clone repository
#         uses: actions/checkout@v4
#       - name: Set up Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: stable
#       - run: flutter pub get
#       - run: flutter test
#       - run: flutter build ios --release --no-codesign
  andRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle
  # webRelease:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: flutter pub get
  #     - run: flutter test
  #     - run: flutter build web
  # windowsRelease:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: flutter build windows
  # linuxRelease:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: |
  #         sudo apt-get update -y
  #         sudo apt-get install -y ninja-build libgtk-3-dev
  #     - run: flutter build linux
  # macRelease:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: flutter build macos
  
