permissions:
  contents: write

on:
  # release:
  #   types: [published]
  #   tags:
  #     - v*
  
  push:
    tags:
      - v*
name: Release
jobs:
#   iosRelease:
#     runs-on: macos-latest
#     steps:
#       - name: Clone repository
#         uses: actions/checkout@v4
#       - name: Set up Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: stable
#       - run: flutter pub get
#       - run: flutter test
#       - run: flutter build ios --release --no-codesign

  androidRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle
      - name: Release apk
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ACTION_RELEASE_TOKEN }}
          files: |
            build/app/outputs/apk/release/*.apk
            LICENSE
  # webRelease:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: flutter pub get
  #     - run: flutter build web --release
  #     - name: zip build
  #       uses: montudor/action-zip@v1
  #       with:
  #         args: zip -qq -r "web_*.zip" "build/web"
  #     - name: Release web
  #       uses: ncipollo/release-action@v1.5.0
  #       with:
  #         artifacts: "web_*.zip"
  #         token: ${{ secrets.ACTION_RELEASE_TOKEN }}
  # windowsRelease:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: flutter build windows --release
  #     - name: zip build
  #       uses: montudor/action-zip@v1
  #       with:
  #         args: zip -qq -r "windows_*.zip" "build\windows\x64\runner\Release"
  #     - name: Release windows
  #       uses: ncipollo/release-action@v1.5.0
  #       with:
  #         artifacts: "windows_*.zip"
  #         token: ${{ secrets.ACTION_RELEASE_TOKEN }}
  # linuxRelease:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: |
  #         sudo apt-get update -y
  #         sudo apt-get install -y ninja-build libgtk-3-dev
  #     - run: flutter build linux
  # macRelease:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: flutter build macos
  
